Fix build error with MinGW on Linux
Linux uses case sensitive file system. So "Windows.h" doesn't exist.

    % make CC=x86_64-w64-mingw32-gcc EXT=.exe SHARD_EXT=dll
    ...
    lz4io.c:69:73: fatal error: Windows.h: No such file or directory
    compilation terminated.
    ...